<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapitre 5 Régression linéaire | Initiation au langage R</title>
  <meta name="description" content="Initiation au langage de programmation, R" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapitre 5 Régression linéaire | Initiation au langage R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Initiation au langage de programmation, R" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapitre 5 Régression linéaire | Initiation au langage R" />
  
  <meta name="twitter:description" content="Initiation au langage de programmation, R" />
  

<meta name="author" content="Cédric HASSEN-KHODJA" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statistiques-descriptives-avec-r.html"/>
<link rel="next" href="les-graphiques-avec-r.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction à R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#quest-ce-que-le-logiciel-r"><i class="fa fa-check"></i><b>1.1</b> Qu’est-ce que le logiciel R ?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#installer-r"><i class="fa fa-check"></i><b>1.2</b> Installer R</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#rstudio-desktop"><i class="fa fa-check"></i><b>1.3</b> RStudio Desktop</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#quelques-commandes-de-base-r"><i class="fa fa-check"></i><b>1.4</b> Quelques commandes de base R</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="le-langage-r.html"><a href="le-langage-r.html"><i class="fa fa-check"></i><b>2</b> Le langage R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="le-langage-r.html"><a href="le-langage-r.html#elément-de-base-du-langage-le-vecteur"><i class="fa fa-check"></i><b>2.1</b> Elément de base du langage : le vecteur</a></li>
<li class="chapter" data-level="2.2" data-path="le-langage-r.html"><a href="le-langage-r.html#opérations-sur-les-vecteurs"><i class="fa fa-check"></i><b>2.2</b> Opérations sur les vecteurs</a></li>
<li class="chapter" data-level="2.3" data-path="le-langage-r.html"><a href="le-langage-r.html#la-matrice-un-objet-à-deux-dimensions"><i class="fa fa-check"></i><b>2.3</b> La matrice : un objet à deux dimensions</a></li>
<li class="chapter" data-level="2.4" data-path="le-langage-r.html"><a href="le-langage-r.html#la-liste"><i class="fa fa-check"></i><b>2.4</b> La liste</a></li>
<li class="chapter" data-level="2.5" data-path="le-langage-r.html"><a href="le-langage-r.html#le-tableau-de-données"><i class="fa fa-check"></i><b>2.5</b> Le tableau de données</a></li>
<li class="chapter" data-level="2.6" data-path="le-langage-r.html"><a href="le-langage-r.html#concaténer-des-objets-r-en-lignes-ou-en-colonnes"><i class="fa fa-check"></i><b>2.6</b> Concaténer des objets R en lignes ou en colonnes</a></li>
<li class="chapter" data-level="2.7" data-path="le-langage-r.html"><a href="le-langage-r.html#les-fonctions-et-les-librairies-packages-r"><i class="fa fa-check"></i><b>2.7</b> Les fonctions et les librairies (packages) R</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="le-langage-r.html"><a href="le-langage-r.html#les-fonctions-r"><i class="fa fa-check"></i><b>2.7.1</b> Les fonctions R</a></li>
<li class="chapter" data-level="2.7.2" data-path="le-langage-r.html"><a href="le-langage-r.html#les-librairies-de-fonctions-sous-r"><i class="fa fa-check"></i><b>2.7.2</b> Les librairies de fonctions sous R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manipulation-des-données-sous-r.html"><a href="manipulation-des-données-sous-r.html"><i class="fa fa-check"></i><b>3</b> Manipulation des données sous R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="manipulation-des-données-sous-r.html"><a href="manipulation-des-données-sous-r.html#importer-un-jeu-de-données-sous-r"><i class="fa fa-check"></i><b>3.1</b> importer un jeu de données sous R</a></li>
<li class="chapter" data-level="3.2" data-path="manipulation-des-données-sous-r.html"><a href="manipulation-des-données-sous-r.html#exporter-un-jeu-de-données-sous-r"><i class="fa fa-check"></i><b>3.2</b> Exporter un jeu de données sous R</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistiques-descriptives-avec-r.html"><a href="statistiques-descriptives-avec-r.html"><i class="fa fa-check"></i><b>4</b> Statistiques descriptives avec R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistiques-descriptives-avec-r.html"><a href="statistiques-descriptives-avec-r.html#médianes-et-quantiles"><i class="fa fa-check"></i><b>4.1</b> Médianes et quantiles</a></li>
<li class="chapter" data-level="4.2" data-path="statistiques-descriptives-avec-r.html"><a href="statistiques-descriptives-avec-r.html#la-moyenne-et-la-somme"><i class="fa fa-check"></i><b>4.2</b> La moyenne et la somme</a></li>
<li class="chapter" data-level="4.3" data-path="statistiques-descriptives-avec-r.html"><a href="statistiques-descriptives-avec-r.html#la-variance-et-lécart-type"><i class="fa fa-check"></i><b>4.3</b> La variance et l’écart-type</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="régression-linéaire.html"><a href="régression-linéaire.html"><i class="fa fa-check"></i><b>5</b> Régression linéaire</a></li>
<li class="chapter" data-level="6" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html"><i class="fa fa-check"></i><b>6</b> Les graphiques avec R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#gestion-des-graphiques-sous-rstudio"><i class="fa fa-check"></i><b>6.1</b> Gestion des graphiques sous RStudio</a></li>
<li class="chapter" data-level="6.2" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#quelques-fonctions-graphiques"><i class="fa fa-check"></i><b>6.2</b> Quelques fonctions graphiques</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#la-fonction-plot"><i class="fa fa-check"></i><b>6.2.1</b> La fonction plot()</a></li>
<li class="chapter" data-level="6.2.2" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#la-fonction-pairs"><i class="fa fa-check"></i><b>6.2.2</b> La fonction pairs()</a></li>
<li class="chapter" data-level="6.2.3" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#la-fonction-pie"><i class="fa fa-check"></i><b>6.2.3</b> La fonction pie()</a></li>
<li class="chapter" data-level="6.2.4" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#la-fonction-hist"><i class="fa fa-check"></i><b>6.2.4</b> La fonction hist()</a></li>
<li class="chapter" data-level="6.2.5" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#la-fonction-barplot"><i class="fa fa-check"></i><b>6.2.5</b> La fonction barplot()</a></li>
<li class="chapter" data-level="6.2.6" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#la-fonction-boxplot"><i class="fa fa-check"></i><b>6.2.6</b> La fonction boxplot()</a></li>
<li class="chapter" data-level="6.2.7" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#les-fonctions-de-tracé-de-courbes-de-niveau"><i class="fa fa-check"></i><b>6.2.7</b> Les fonctions de tracé de courbes de niveau</a></li>
<li class="chapter" data-level="6.2.8" data-path="les-graphiques-avec-r.html"><a href="les-graphiques-avec-r.html#les-fonctions-de-cartographie"><i class="fa fa-check"></i><b>6.2.8</b> Les fonctions de cartographie</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="liens-utiles.html"><a href="liens-utiles.html"><i class="fa fa-check"></i><b>7</b> Liens utiles</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Initiation au langage R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="régression-linéaire" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapitre 5</span> Régression linéaire<a href="régression-linéaire.html#régression-linéaire" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>La régression linéaire est une méthode statistique utilisée pour modéliser la <strong>relation entre une variable dépendante et une ou plusieurs variables indépendantes</strong>. Sous R, il est possible d’effectuer une régression linéaire à l’aide de la fonction <code>lm()</code>.<br />
La régression linéaire simple (une seule variable explicative) s’écrit:</p>
<blockquote>
<p>lm(y~x)</p>
</blockquote>
<p>Dans l’exemple suivant, on va tester la relation entre le poids et lâge des poussins.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="régression-linéaire.html#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chargement du jeu de données</span></span>
<span id="cb107-2"><a href="régression-linéaire.html#cb107-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ChickWeight&quot;</span>)</span>
<span id="cb107-3"><a href="régression-linéaire.html#cb107-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-4"><a href="régression-linéaire.html#cb107-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight<span class="sc">~</span>Time, <span class="at">data =</span> ChickWeight)</span>
<span id="cb107-5"><a href="régression-linéaire.html#cb107-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ Time, data = ChickWeight)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -138.331  -14.536    0.926   13.533  160.669 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  27.4674     3.0365   9.046   &lt;2e-16 ***
## Time          8.8030     0.2397  36.725   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 38.91 on 576 degrees of freedom
## Multiple R-squared:  0.7007, Adjusted R-squared:  0.7002 
## F-statistic:  1349 on 1 and 576 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Ce résultat concerne un modèle de régression linéaire simple pour prédire le poids des poussins en fonction de leur âge. Voici comment interpréter les différents éléments :</p>
<blockquote>
<ul>
<li>Call : Cette ligne indique la formule de régression utilisée, qui est “weight ~ Time” et le nom du data.frame utilisé, qui est “ChickWeight”.</li>
<li>Coefficients : Cette section présente les coefficients de la régression. L’intercept (l’ordonnée à l’origine) est de 27,4674 et la pente pour la variable “Time” est de 8,8030. Cela signifie que pour chaque unité de temps supplémentaire (jours), le poids des poussins augmente en moyenne de 8,8030.</li>
<li>Pr(&gt;|t|) : Cette colonne donne la p-value pour chaque coefficient. Les p-values très faibles (&lt; 0,001) indiquent que les coefficients sont significatifs et que la probabilité d’obtenir une telle valeur de t par hasard est très faible.</li>
<li>Residual standard error : C’est une estimation de l’écart-type des résidus. Cela mesure la variabilité non expliquée du modèle. Dans ce cas, l’écart-type est de 38,91.</li>
<li>Multiple R-squared : C’est le coefficient de détermination qui mesure la proportion de la variance totale expliquée par le modèle. Ici, le R² est de 0,7007, ce qui indique que le modèle explique 70,07 % de la variance totale des données.</li>
<li>F-statistic : Il s’agit d’un test statistique global de la significativité du modèle. Dans ce cas, le F-statistic est de 1349 avec 1 et 576 degrés de liberté, ce qui est très significatif.</li>
<li>p-value : C’est la p-value associée au test F et indique la probabilité d’obtenir une telle valeur de F par hasard. La p-value est très faible (&lt; 2,2e-16), ce qui indique que le modèle est très significatif.</li>
</ul>
</blockquote>
<p><strong>En résumé, ce modèle de régression linéaire simple montre qu’il existe une relation positive significative entre le poids des poussins et leur âge. Le modèle explique environ 70 % de la variance totale des données et est très significatif.</strong></p>
<p>Ajoutons maintenant le régime alimentaire des poussins en compte. Voyons maintenant l’effet de l’âge et du régime alimentaire sur le poids des poussins.
Le modèle devient:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="régression-linéaire.html#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#chargement du jeu de données</span></span>
<span id="cb109-2"><a href="régression-linéaire.html#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ChickWeight&quot;</span>)</span>
<span id="cb109-3"><a href="régression-linéaire.html#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="régression-linéaire.html#cb109-4" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight<span class="sc">~</span>Time<span class="sc">*</span>Diet, <span class="at">data =</span> ChickWeight)</span>
<span id="cb109-5"><a href="régression-linéaire.html#cb109-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = weight ~ Time * Diet, data = ChickWeight)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -135.425  -13.757   -1.311   11.069  130.391 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  30.9310     4.2468   7.283 1.09e-12 ***
## Time          6.8418     0.3408  20.076  &lt; 2e-16 ***
## Diet2        -2.2974     7.2672  -0.316  0.75202    
## Diet3       -12.6807     7.2672  -1.745  0.08154 .  
## Diet4        -0.1389     7.2865  -0.019  0.98480    
## Time:Diet2    1.7673     0.5717   3.092  0.00209 ** 
## Time:Diet3    4.5811     0.5717   8.014 6.33e-15 ***
## Time:Diet4    2.8726     0.5781   4.969 8.92e-07 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 34.07 on 570 degrees of freedom
## Multiple R-squared:  0.773,  Adjusted R-squared:  0.7702 
## F-statistic: 277.3 on 7 and 570 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Cette régression linéaire est un modèle plus complexe que le précédent car il inclut non seulement l’effet de l’âge sur le poids des poussins, mais aussi l’effet du régime alimentaire sur leur poids. De plus, il inclut également une <strong>interaction entre l’âge et la diète</strong>, ce qui permet d’explorer si l’effet de l’âge sur le poids varie selon la diète.</p>
<p>Voici comment interpréter les résultats :</p>
<blockquote>
<ul>
<li>Pour l’intercept, Diet1 est pris comme référence. Si nous considérons que la référence (Diet1) a un poids initial moyen de 30.9310g, le coefficient pour Diet2 indique que les poussins ont un poids initial de 28.6336g (30.9310 - 2.2974) lorsqu’ils ont commencé l’expérience.</li>
<li>Le coefficient pour Time indique que, toutes choses égales par ailleurs, le poids des poussins augmente de 6.8418g chaque jour qui passe.</li>
<li>Les coefficients pour Time:Diet2, Time:Diet3, et Time:Diet4 indiquent l’effet de l’interaction entre le temps et la diète respective sur le poids des poussins. Par exemple, le coefficient pour Time:Diet3 indique que l’effet, de chaque jour supplémentaire sur le poids des poussins, est amplifié de 4.5811g pour les poussins qui reçoivent Diet3, comparé à ceux qui reçoivent la diète de référence.</li>
<li>La valeur de l’erreur standard résiduelle (Residual standard error) est de 34.07, ce qui indique l’erreur standard moyenne dans les prévisions du poids des poussins que le modèle ne peut pas expliquer.</li>
<li>Le R-carré multiple (Multiple R-squared) indique la proportion de la variance totale qui est expliquée par le modèle, et est égal à 0.773. Cela signifie que le modèle explique environ 77,3% de la variation totale des données.</li>
<li>L’ajustement du R-carré (Adjusted R-squared) est égal à 0.7702. Cela signifie que le modèle ajusté explique environ 77,0% de la variation des données.</li>
<li>Le test F, avec une statistique de test de 277.3 et une p-value très faible, indique que le modèle dans son ensemble est significatif.</li>
</ul>
</blockquote>
<p><strong>En résumé, ce modèle de régression linéaire montre qu’il existe une relation significative à la fois entre le poids des poussins, leur âge et le régime alimentaire reçu. Le modèle explique environ 77 % de la variance totale des données et est très significatif.</strong></p>
<p><strong>Exercice 3:</strong></p>
<p>Le jeu de données <strong>iris</strong> intégré dans R contient des mesures sur différentes espèces d’iris. Nous allons utiliser la longueur du pétale (Petal.Length) pour prédire la largeur du pétale (Petal.Width).</p>
<ol style="list-style-type: decimal">
<li>Charger le jeu de données “iris” en utilisant la fonction <code>data()</code>.</li>
<li>Examiner les données en utilisant la fonction <code>head()</code> et <code>summary()</code>.</li>
<li>Créer un graphique de dispersion de Petal.Length vs Petal.Width en utilisant la fonction <code>plot()</code>.</li>
<li>Ajuster un modèle de régression linéaire simple pour prédire Petal.Width à partir de Petal.Length.</li>
<li>Résumer les résultats de la régression en utilisant la fonction <code>summary()</code>.</li>
<li>Utiliser le modèle pour faire une prédiction de la largeur du pétale pour une fleur avec une longueur de pétale de 6 cm.</li>
<li>Tracer la ligne de régression sur le graphique de dispersion en utilisant la fonction <code>abline()</code>.</li>
</ol>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="statistiques-descriptives-avec-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="les-graphiques-avec-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/04-reg-linéaire.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R bookdown.pdf", "R bookdown.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
